### ISSUE TITLE
Pick a swiss-army-knife library

### ISSUE THREAD

**Issue by ianb** [ianb/pageshot#120]
We need some kind of utility library, maybe more than one.  Examples would be Underscore or Lodash.

Some things I would like:

- Some light class syntax (ideally similar to [this pattern](http://www.ianbicking.org/blog/2013/04/new-considered-harmful.html))
- Ability to mixin and extend objects (extending a prototype can be akin to subclassing)
- Event emitting and binding
- Promises, and maybe some helpers associated with promises
- Some string utilities, like trim, startswith, etc.  Something that compiles down ES6 might be sufficient
- Assertions
- Logging
- URL handling (for constructing and parsing URLs)
- Maybe some array helpers
- Some helpers for looping over objects, getting keys, etc.  Though Object now has some of the necessary functions anyway, we might not need this.

Lodash and Underscore don't actually do that great on this list, I think.  They tend to emphasize what I will call a clever functional style.

I'd like to figure out a way to make this library usable from content, content workers, and ideally even regular addon code.  The last case may be challenging.

**Comment by chrisdickinson** [comment]
You might look at something like 6to5 for polyfilling some of these needs. 

> Some light class syntax (ideally similar to this pattern)

Something like 6to5 should be able to give you this relatively cheaply.

> Ability to mixin and extend objects (extending a prototype can be akin to subclassing)

For object prototype linking, `Object.create` (via es5-shim or es6-shim) works pretty well. For extending, `Object.assign` should be available in es6-shim & 6to5 (AFAIK).

> Promises, and maybe some helpers associated with promises
> Event emitting and binding
> Some string utilities, like trim, startswith, etc. Something that compiles down ES6 might be sufficient
> Assertions
> Logging
> URL handling (for constructing and parsing URLs)

`new URL(string)` is builtin – but a handy hack for browsers that don't support it is to create an anchor element, assign its href, and all of the properties you need will be available on the object. E.g.,

```javascript
var a = document.createElement('a');
a.href = url;
a.host // will be the host portion of the URL
```

> Maybe some array helpers

ES5 has a lot of builtins (some are weirdly named coming from python – `any` and `all` are available as `[].some` and `[].every`, for example. `map`, `filter`, and `reduce` are all available as well.

> Some helpers for looping over objects, getting keys, etc. Though Object now has some of the necessary functions anyway, we might not need this.

I would recommend taking a look [at Addy Osmani's es6-tools list](https://github.com/addyosmani/es6-tools) if you haven't seen it – a lot of these needs are covered by `Array` and `String` builtin methods, `Object.assign` / `Object.create` / `Object.keys(obj)`, or new ES6 syntax (classes) via 6to5 and friends.

For my part, I've found great success with the browserify ecosystem, primarily because it allows me to use packages from the npm ecosystem and neatly solves the building and watching steps. Others like webpack – either way, I'd say that adopting a bundler of some sort will make things a lot easier, and eliminate the need for one library to fulfill everything on your list. I'd be happy to chat about this – I'm on irc.freenode.net as chrisdickinson in `#browserify`. Sorry to drop in with recommendations – I'll buzz off after this unless you'd like to talk! Best of luck!

**Comment by fzzzy** [comment]
I'm +1 on using 6to5 or another use-es6-now library. es6 is a much nicer language than javascript is today, and we can use generators to emulate green threads.

**Comment by ianb** [comment]
It is decided, 6to5!
